{
 "title": "Condition Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  temperature\nFROM data\nORDER  BY aq_time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  max(temperature)\nFROM data"
    }
   ]
  },
  {
   "title": "Current humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  humidity\nFROM data\nORDER BY aq_time desc\nLIMIT 1 "
    }
   ]
  },
  {
   "title": "Max humidity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  max(humidity)\nFROM data"
    }
   ]
  },
  {
   "title": "Min temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  min(temperature)\nFROM data"
    }
   ]
  },
  {
   "title": "Min humidity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  min(humidity)\nFROM data"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT id, aq_time, temperature, humidity FROM data"
    }
   ]
  },
  {
   "title": "Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  aq_time AS \"time\",\n  temperature,\n  humidity\nFROM data\nORDER BY aq_time"
    }
   ]
  }
 ]
}